CREATE TABLE jobs (
    uuid UUID NOT NULL PRIMARY KEY,
    payload JSONB NOT NULL,
    status TEXT NOT NULL DEFAULT 'CREATED',
    retry_after_seconds INT NOT NULL DEFAULT 30,
    created TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ON jobs (status);
